features:
  pvp: true
  plotcalculate: true
  fitness: true
  levelcheck: true
  wage: true
  costs: true
  books: true
  fine: true
  receipt: true
  identification: true
  kvk: true
  plotregistration: true
  driverslicense: true
  colors: true
  labymod: true
  currencies: true
  transactions: true
  time: true
  teleporter: true
  staff: true
  skript: true
  scoreboard: true
  restapi: true
  prefix: true
  portal: true
  police: true
  plots: true
  player: true
  places: true
  misc: true
  lock: true
  items: true
  detectiongates: true
  data: true
  core: true
  chat: true
  banking: true

pvp:
  enabled: true
  items:
    - item:
        type: STICK
      attacker-message: "<red>Je hebt <dark_red><victim> <red>geslagen met jouw knuppel"
      victim-message: "<red>Je bent geslagen met een knuppel!"
    - item:
        type: FERMENTED_SPIDER_EYE
      attacker-message: "<red>Je hebt <dark_red><victim> <red>geslagen met jouw wapenstok"
      victim-message: "<red>Je bent geslagen met een wapenstok!"
    - item:
        type: STONE_AXE
      attacker-message: "<red>Je hebt <dark_red><victim> <red>geslagen met jouw knuppel"
      victim-message: "<red>Je bent geslagen met een knuppel!"
    - item:
        type: STONE_HOE
      attacker-message: "<red>Je hebt <dark_red><victim> <red>geslagen met jouw knuppel"
      victim-message: "<red>Je bent geslagen met een knuppel!"
    - item:
        type: WOODEN_SWORD
      attacker-message: "<red>Je hebt <dark_red><victim> <red>gestoken met jouw mes"
      victim-message: "<red>Je bent gestoken met een mes!"
    - item:
        type: SNOWBALL
      attacker-message: "<red>Je hebt <dark_red><victim> <red>geraakt met jouw sneeuwbal"
      victim-message: "<red>Je bent geraakt met een sneeuwbal!"
    - item:
        type: ARROW
      attacker-message: "<red>Je hebt <dark_red><victim> <red>geraakt met jouw schot"
      victim-message: "<red>Je bent geraakt met een schot!"